title: <p align="center"> Jenny Trang </p>

logo: "/images/picture.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/Profile.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/nguyen-trang2000/">LinkedIn</a> |
  <a href="https://github.com/jasminechann">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing an advanced course in Data Analytics
  <br><br>
College graduate attentive to data. Passionate about studying how to improve performance. Seeking to leverage data analytical skills to improve corporate performance as a data analyst.
  <br><br>
  Bachelor's degree in International Economics at Foreign Trade University
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-SF36VWYWBT # Google Analytics tracking ID
