title: <p align="center"> Jenny Trang </p>

logo: "https://github.com/jasminechann/jasminechann.github.io/blob/a279fd7457c3b76975b03a38e05caf0a76811e14/images/picture.jpg"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/nguyen-trang2000/">LinkedIn</a> |
  <a href="https://github.com/jasminechann">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Business Analytics at Simon Business School, Foreign Trade University.
  <br><br>
  I am currently a Machine Learning Research Intern at Skim AI Technologies with a focus on NLP and Deep Learning research.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: 314022496 # Google Analytics tracking ID
