title: <p align="center"> Trang Nguyen </p>

logo: "/images/picture.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/CV_TRANGNTH_ENG.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/trang-nguyen-02954329b/">LinkedIn</a> |
  <a href="https://github.com/jasminechann">GitHub</a>
  </p>
  
  <p align="justify">
  I deliver actionable data insights to support business decision - making through analytics.
  <br>
  International Economics at Foreign Trade University
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-SF36VWYWBT # Google Analytics tracking ID
